Support XmlDownload.aspx
picqer/exact-php-client pull request #536
Opened 2022-02-03 13:45 UTC by abrampl

2022-02-28 13:57 UTC, abrampl reviewed
Fix new entry line

2022-04-08 09:49 UTC, faizanakram99 requested changes

2022-04-08 09:49 UTC, faizanakram99 commented on src/Picqer/Financials/Exact/Connection.php
> +            $simpleXml = new \SimpleXMLElement($response->getBody()->getContents());
```suggestion
            $simpleXml = new \SimpleXMLElement($response->getBody()->__toString());
```

If `__toString()` is used, there is no need to manually rewind stream. `StreamInterface::getContents()` behaviour is inconsistent across different psr 7 libraries.

https://www.php-fig.org/psr/psr-7/#13-streams

2022-07-22 11:55 UTC, faizanakram99 approved these changes

2022-08-14 13:06 UTC, stephangroen commented
Any explanation on what this is?

2022-08-16 12:04 UTC, faizanakram99 commented
> Any explanation on what this is?

@stephangroen 
From https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-xmlintro
> Exact Online XML API - Introduction
> In Exact Online you can manually import and export data using the XML API. You can also exchange data from external applications automatically. This allows Exact Online to integrate seamlessly with solutions developed by external software suppliers.
> 
> The Exact Online XML API can easily be integrated in external applications by requesting the XMLDownload.aspx or the XMLUpload.aspx and specifying the topic which needs to be downloaded or uploaded with some optional parameters.
> 
> For all API requests, you are required to authenticate the request.

Some code examples here
https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-xmlsamplecode

2022-10-03 14:32 UTC, mvdgeijn commented
Accepting this pull request would be much appreciated. I was already working on the same.

2022-10-03 14:55 UTC, stephangroen requested changes
Thanks. Please fix the one line failing in the style, and I'll merge the PR.

2022-10-11 06:30 UTC, stephangroen commented
Fixed in #586

2022-10-11 06:30 UTC, closed without merging